/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:4adb3e02-d9ba-4177-8a2f-5b3171b26b77",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_R7IGkfkyQ",
    "aws_user_pools_web_client_id": "5434ngqtrsheckk4uirj1crb4n",
    "oauth": {}
};


export default awsmobile;
